import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import { Toaster } from "sonner"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} flex flex-col min-h-screen relative bg-gray-900`}
			>
				{/* SVG Background Layer */}
				<div
					className="fixed inset-0 bg-no-repeat bg-center bg-cover pointer-events-none opacity-20"
					style={{ backgroundImage: "url('/bg.svg')" }}
				></div>

				<Toaster closeButton={true} richColors={true} />
				<Navbar />
				<main className="flex-grow relative">{children}</main>
				<Footer />
			</body>
		</html>
	)
}
